### ISSUE TITLE
Logs cannot detect /tweet /ad /ooc /anontweet /me

### ISSUE THREAD

**Issue by BryBTG** [Tazi0/Server-Logging#3]
Logs cannot detect /tweet /ad /ooc /anontweet /me they are not appearing on the discord webhook.

**Comment by Tazi0** [comment]
![image](https://user-images.githubusercontent.com/45716542/57878105-9de42180-7819-11e9-97c9-c11a66b4d73f.png)
![image](https://user-images.githubusercontent.com/45716542/57878147-b3594b80-7819-11e9-9801-c8af6a4e9563.png)
![image](https://user-images.githubusercontent.com/45716542/57878213-d421a100-7819-11e9-9e09-81f8a96663e3.png)
![image](https://user-images.githubusercontent.com/45716542/57878229-ddab0900-7819-11e9-8b5a-0f017a602015.png)
They work fine for me, try a different /tweet command or something. 🤷‍♂

**Comment by ghost** [comment]
Could you give an example, or explain it, it would be very nice 🙃😂😉
