### ISSUE TITLE
Double Kill-Logs

### ISSUE THREAD

**Issue by wydox1SK** [Tazi0/Server-Logging#6]
Hey, installed this resource last night and am having an issue where it shows double logs for kills as seen here; https://i.gyazo.com/997f45b5348d17613a5c4fc4187a849c.png

**Comment by Tazi0** [comment]
looking into it

**Comment by Tazi0** [comment]
Do you have any other active log?

**Comment by Tazi0** [comment]
Could be 2 active loggers
