### ISSUE TITLE
Everything into 1 discord channel

### ISSUE THREAD

**Issue by Missterica** [Tazi0/Server-Logging#9]
I noticed that this logger just drops everything into 1 channel. it would be so much more usefull to have the join and connect into 1 webhook, then the kill messages into 1 webhook. and the chat the same. even the /me do commands from RP chat into another log. or maybe you have another chat script that you can recommend?

**Comment by Tazi0** [comment]
You can split them, just change the `DISCORD_WEBHOOK` at

 https://github.com/Tazi0/Server-Logging/blob/980f43d1efa0957481d357d130864bf42b838e0f/Serverlogging/server.lua#L23

and
https://github.com/Tazi0/Server-Logging/blob/980f43d1efa0957481d357d130864bf42b838e0f/Serverlogging/server.lua#L28
